import type { FeedTab, JobDetail, JobListRow } from "./types";

/** Fixed UUIDs — match `supabase/snippets/seed_demo_jobs.sql` if you seed the DB */
export const SEED_JOB_IDS = {
  hot: "a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11",
  featured: "b0eebc99-9c0b-4ef8-bb6d-6bb9bd380a12",
  rec: "c0eebc99-9c0b-4ef8-bb6d-6bb9bd380a13",
  invited: "d0eebc99-9c0b-4ef8-bb6d-6bb9bd380a14",
  saved: "e0eebc99-9c0b-4ef8-bb6d-6bb9bd380a15",
} as const;

const MOCK_JOBS: JobListRow[] = [
  {
    id: SEED_JOB_IDS.hot,
    jobId: "JOB#A0EEBC99",
    tab: "available",
    title: "SPRING AAU\nSHOWCASE",
    org: "TEXAS HOOPS ORG",
    orgVerified: true,
    pay: "185",
    payUnit: "/ GAME",
    date: "SAT 5/4",
    time: "9 AM · 4H",
    crew: "3-PERSON",
    dist: "12.4 MI",
    tags: ["U16", "BOYS"],
    variant: "hot",
    tagLeft: "2 SLOTS LEFT",
    footerCta: "ACCEPT →",
    footerCtaTone: "ink",
    startsAtIso: "2026-05-04T14:00:00-05:00",
    payPerGame: 185,
    crewSize: 3,
    level: "youth",
    ageGroup: "U16",
    distanceMiles: 12.4,
  },
  {
    id: SEED_JOB_IDS.featured,
    jobId: "JOB#B0EEBC99",
    tab: "available",
    title: "LAKEWAY\nTOURNAMENT",
    org: "LAKEWAY SPORTS GRP",
    orgVerified: true,
    pay: "420",
    payUnit: "/ DAY",
    date: "SUN 5/5",
    time: "8 AM · FULL",
    crew: "3-PERSON",
    dist: "18.7 MI",
    tags: ["U18", "GIRLS"],
    variant: "featured",
    tagLeft: "FEATURED · MULTI-DAY",
    footerCta: "VIEW →",
    footerCtaTone: "signal",
    startsAtIso: "2026-05-05T13:00:00-05:00",
    payPerGame: 420,
    crewSize: 3,
    level: "youth",
    ageGroup: "U18",
    distanceMiles: 18.7,
  },
  {
    id: SEED_JOB_IDS.rec,
    jobId: "JOB#C0EEBC99",
    tab: "available",
    title: "AUSTIN REC\nCOURT 3",
    org: "AUSTIN PARKS & REC",
    pay: "85",
    payUnit: "/ GAME",
    date: "TUE 5/7",
    time: "6 PM · 1.5H",
    crew: "2-PERSON",
    dist: "3.1 MI",
    tags: ["ADULT", "CO-ED"],
    variant: "default",
    tagLeft: "REC · WEEKNIGHT",
    footerCta: "VIEW →",
    footerCtaTone: "muted",
    startsAtIso: "2026-05-07T23:00:00-05:00",
    payPerGame: 85,
    crewSize: 2,
    level: "adult",
    ageGroup: "adult",
    distanceMiles: 3.1,
  },
  {
    id: SEED_JOB_IDS.invited,
    jobId: "JOB#D0EEBC99",
    tab: "invited",
    title: "CAPITAL CITY\nCLASSIC",
    org: "CTX BASKETBALL",
    orgVerified: true,
    pay: "200",
    payUnit: "/ GAME",
    date: "FRI 5/9",
    time: "5 PM · 2H",
    crew: "3-PERSON",
    dist: "8.0 MI",
    tags: ["HS", "BOYS"],
    variant: "default",
    tagLeft: "INVITED · 48H",
    footerCta: "VIEW →",
    footerCtaTone: "signal",
    startsAtIso: "2026-05-09T17:00:00-05:00",
    payPerGame: 200,
    crewSize: 3,
    level: "high_school",
    ageGroup: "HS",
    distanceMiles: 8.0,
  },
  {
    id: SEED_JOB_IDS.saved,
    jobId: "JOB#E0EEBC99",
    tab: "saved",
    title: "WEEKEND\nSKILLS CAMP",
    org: "HOOP HOUSE ATX",
    pay: "120",
    payUnit: "/ SESSION",
    date: "SAT 5/11",
    time: "10 AM · 3H",
    crew: "2-PERSON",
    dist: "6.2 MI",
    tags: ["U14", "MIXED"],
    variant: "default",
    tagLeft: "SAVED",
    footerCta: "VIEW →",
    footerCtaTone: "muted",
    startsAtIso: "2026-05-11T10:00:00-05:00",
    payPerGame: 120,
    crewSize: 2,
    level: "youth",
    ageGroup: "U14",
    distanceMiles: 6.2,
  },
];

const MOCK_DETAILS: Record<string, JobDetail> = {
  [SEED_JOB_IDS.hot]: {
    id: SEED_JOB_IDS.hot,
    jobCode: "#A0EEBC99-A",
    telemetryLeft: "2 SLOTS LEFT · CLOSES IN 4H 22M",
    telemetryRight: "LIVE",
    heroTag: "FEATURED · TOURNAMENT",
    title: "SPRING AAU SHOWCASE",
    org: "TEXAS HOOPS ORG",
    orgVerified: true,
    payTotal: 740,
    payPerGame: 185,
    numGames: 4,
    payoutHours: 48,
    whenPrimary: "SAT 5/4",
    whenSecondary: "9:00 AM CT",
    whenTertiary: "~ 4 HR BLOCK",
    wherePrimary: "ROUND ROCK",
    whereSecondary: "EASTSIDE SPORTS COMPLEX",
    whereTertiary: "12.4 MI · ~22 MIN",
    venueName: "EASTSIDE SPORTS COMPLEX",
    venueAddress: "2400 MAYS ST · ROUND ROCK, TX",
    crewSize: 3,
    sportLabel: "BASKETBALL",
    levelLabel: "U16 · BOYS",
    ruleset: "NFHS",
    gameLength: "4 × 8 MIN",
    uniform: "BLACK / WHITE STRIPE",
    parking: "FREE · ON-SITE",
    hirerNote:
      "Crew arrives 15 min early for pre-game review. Concessions onsite. Reach the organizer at the score table for any questions during the day.",
    slotsOpen: 2,
    closesInLabel: "4H 22M",
    isFeatured: true,
    variant: "hot",
  },
  [SEED_JOB_IDS.featured]: {
    id: SEED_JOB_IDS.featured,
    jobCode: "#B0EEBC99-D2",
    telemetryLeft: "FEATURED · MULTI-DAY",
    telemetryRight: "OPEN",
    heroTag: "FEATURED · MULTI-DAY",
    title: "LAKEWAY TOURNAMENT",
    org: "LAKEWAY SPORTS GRP",
    payTotal: 420,
    payPerGame: 420,
    numGames: 1,
    payoutHours: 48,
    whenPrimary: "SUN 5/5",
    whenSecondary: "8:00 AM CT",
    whenTertiary: "FULL DAY",
    wherePrimary: "LAKEWAY",
    whereSecondary: "LAKEWAY HS GYM",
    whereTertiary: "18.7 MI · ~35 MIN",
    venueName: "LAKEWAY HS GYM",
    venueAddress: "3324 LAKEWAY BLVD · LAKEWAY, TX",
    crewSize: 3,
    sportLabel: "BASKETBALL",
    levelLabel: "U18 · GIRLS",
    ruleset: "NFHS",
    gameLength: "2 × 20 MIN",
    uniform: "GREY SHIRT",
    parking: "LOT B",
    hirerNote: "Check in at main entrance. Bring two whistles.",
    slotsOpen: 1,
    closesInLabel: "2D 08H",
    isFeatured: true,
    variant: "featured",
  },
  [SEED_JOB_IDS.rec]: {
    id: SEED_JOB_IDS.rec,
    jobCode: "#C0EEBC99-R",
    telemetryLeft: "REC · WEEKNIGHT",
    telemetryRight: "OPEN",
    heroTag: "REC LEAGUE",
    title: "AUSTIN REC COURT 3",
    org: "AUSTIN PARKS & REC",
    payTotal: 85,
    payPerGame: 85,
    numGames: 1,
    payoutHours: 48,
    whenPrimary: "TUE 5/7",
    whenSecondary: "6:00 PM CT",
    whenTertiary: "~ 1.5 HR",
    wherePrimary: "AUSTIN",
    whereSecondary: "REC CENTER — CT 3",
    whereTertiary: "3.1 MI · ~12 MIN",
    venueName: "AUSTIN REC CENTER",
    venueAddress: "RECREATION LN · AUSTIN, TX",
    crewSize: 2,
    sportLabel: "BASKETBALL",
    levelLabel: "ADULT · CO-ED",
    ruleset: "FIBA",
    gameLength: "2 × 12 MIN",
    uniform: "BLACK / WHITE",
    parking: "STREET",
    hirerNote: null,
    slotsOpen: 2,
    closesInLabel: null,
    isFeatured: false,
    variant: "default",
  },
  [SEED_JOB_IDS.invited]: {
    id: SEED_JOB_IDS.invited,
    jobCode: "#D0EEBC99-I",
    telemetryLeft: "INVITED · RESPOND IN 48H",
    telemetryRight: "INVITE",
    heroTag: "INVITED",
    title: "CAPITAL CITY CLASSIC",
    org: "CTX BASKETBALL",
    payTotal: 200,
    payPerGame: 200,
    numGames: 1,
    payoutHours: 48,
    whenPrimary: "FRI 5/9",
    whenSecondary: "5:00 PM CT",
    whenTertiary: "~ 2 HR",
    wherePrimary: "AUSTIN",
    whereSecondary: "DOWNTOWN ARENA",
    whereTertiary: "8.0 MI · ~18 MIN",
    venueName: "DOWNTOWN ARENA",
    venueAddress: "200 ARENA WAY · AUSTIN, TX",
    crewSize: 3,
    sportLabel: "BASKETBALL",
    levelLabel: "HS · BOYS",
    ruleset: "NFHS",
    gameLength: "4 × 8 MIN",
    uniform: "STRIPED",
    parking: "GARAGE PAID",
    hirerNote: "Playoff intensity — arrive early.",
    slotsOpen: 1,
    closesInLabel: "48H",
    isFeatured: false,
    variant: "default",
  },
  [SEED_JOB_IDS.saved]: {
    id: SEED_JOB_IDS.saved,
    jobCode: "#E0EEBC99-S",
    telemetryLeft: "SAVED FOR LATER",
    telemetryRight: "OPEN",
    heroTag: "SKILLS CAMP",
    title: "WEEKEND SKILLS CAMP",
    org: "HOOP HOUSE ATX",
    payTotal: 120,
    payPerGame: 120,
    numGames: 1,
    payoutHours: 48,
    whenPrimary: "SAT 5/11",
    whenSecondary: "10:00 AM CT",
    whenTertiary: "~ 3 HR",
    wherePrimary: "AUSTIN",
    whereSecondary: "HOOP HOUSE",
    whereTertiary: "6.2 MI · ~15 MIN",
    venueName: "HOOP HOUSE",
    venueAddress: "NORTH LOOP · AUSTIN, TX",
    crewSize: 2,
    sportLabel: "BASKETBALL",
    levelLabel: "U14 · MIXED",
    ruleset: "YOUTH MOD",
    gameLength: "STATIONS",
    uniform: "ANY GREY",
    parking: "FREE",
    hirerNote: null,
    slotsOpen: 3,
    closesInLabel: null,
    isFeatured: false,
    variant: "default",
  },
};

export function getMockJobs(): JobListRow[] {
  return MOCK_JOBS;
}

export function getMockJobListRowsForTab(tab: FeedTab): JobListRow[] {
  return MOCK_JOBS.filter((j) => j.tab === tab);
}

export function getMockJobDetail(id: string): JobDetail | null {
  return MOCK_DETAILS[id] ?? null;
}
